### ISSUE TITLE
Add possibility to use the "Skip" parameter of the ARM-TTK module

### ISSUE THREAD

**Issue by samrobillard** [sam-cogan/arm-ttk-extension#11]
Hi,

Some ARM templates like policy definitions might require empty properties in the template but doing so fails the test that checks for empty properties. Locally, I use the "Skip" parameter to work around that until the issue I raised with arm-ttk is addressed. But, it doesn't seem to be possible in the Azure DevOps extension. Would it be possible to add that feature?

Thanks,

**Comment by sam-cogan** [comment]
This is a great idea, I'll look to add it.
