### ISSUE TITLE
Get ARM-TTKK latest repo version on each run

### ISSUE THREAD

**Issue by samrobillard** [sam-cogan/arm-ttk-extension#12]
Hi,

Would it be possible for the extension to update its content before each run? The ARM-TTK repo contains a few fixes that are not present in this extension.

Thanks,

**Comment by sam-cogan** [comment]
I do update the extension when releasing a new version, would esurinf rebuild a new version when there is a change to the TTk help, rather than downloading every time you run it?

**Comment by sam-cogan** [comment]
The template was updated this weekend with the latest tests
