### ISSUE TITLE
IDs Should Be Derived From ResourceIDs fails in vnet template

### ISSUE THREAD

**Issue by drawshah** [sam-cogan/arm-ttk-extension#18]
Using the Azure DevOps task:

- task: RunARMTTKTests@1
      inputs:
        templatelocation: '$(System.DefaultWorkingDirectory)\Templates'
        resultLocation: '$(System.DefaultWorkingDirectory)\results'

 i get the following error when it is testing the template at the bottom of post

Error message
Microsoft.PowerShell.Commands.WriteErrorException: Blank ID Property found:
id ParentObject

[resourceId('Microsoft.Network/networkSecurityGroups', parameters('nsg-name'))] {@{addressPrefix=[parameters('vnetAd...

in template file vnet_template.json
Stack trace
at <ScriptBlock>, D:\a_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\arm-ttk\testcases\deploymentTemplate\IDs-Should-Be-Derived-From-ResourceIDs.test.ps1: line 61
at Test-Case, D:\a_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\arm-ttk\Test-AzTemplate.ps1: line 190
at Test-Group, D:\a_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\arm-ttk\Test-AzTemplate.ps1: line 214
at Test-FileList, D:\a_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\arm-ttk\Test-AzTemplate.ps1: line 334
at Test-AzTemplate<End>, D:\a_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\arm-ttk\Test-AzTemplate.ps1: line 480
at Test-FolderContents, D:\a_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\invoke-ttk.psm1: line 12
at Invoke-TTK, D:\a_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\invoke-ttk.psm1: line 75
at <ScriptBlock>, D:\a_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.6\powershell.ps1: line 28
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 22
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 1

vnet_template.json

{
"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
"contentVersion": "1.0.0.0",
"parameters": {
"location": {
"type": "string"
},
"nsg-name": {
"type": "string",
"defaultValue": "test-nsg"
},
"virtualNetworkName": {
"type": "string"
},
"vnetAddressPrefix": {
"type": "string"
}
},
"variables": {},
"resources": [
{
"type": "Microsoft.Network/networkSecurityGroups",
"name": "[parameters('nsg-name')]",
"apiVersion": "2020-04-01",
"location": "[parameters('location')]",
"properties": {}
},
{
"type": "Microsoft.Network/virtualNetworks",
"name": "[parameters('virtualNetworkName')]",
"apiVersion": "2020-04-01",
"location": "[parameters('location')]",
"dependsOn": [
"[resourceId('Microsoft.Network/networkSecurityGroups', parameters('nsg-name'))]"
],
"properties": {
"addressSpace": {
"addressPrefixes": [
"[parameters('vnetAddressPrefix')]"
]
},
"subnets": [
{
"name": "default",
"properties": {
"addressPrefix": "[parameters('vnetAddressPrefix')]",
"networkSecurityGroup": {
"id": "[resourceId('Microsoft.Network/networkSecurityGroups', parameters('nsg-name'))]"
}
}
}
],
"enableDdosProtection": false,
"enableVmProtection": false
}
}
],
"outputs": {
"ip-prefix": {
"type": "string",
"value": "[resourceId('Microsoft.Network/virtualNetworks', parameters('virtualNetworkName'))]"
}
}
}

**Comment by sam-cogan** [comment]
This is an issue with the TTK rather than the extension, I have replicated it using the TTK alone. I'll reply to the TTK issue you raised.

**Comment by sam-cogan** [comment]
Yep, looks like it is an issue with the age of some of the TTK files in the extension. I had though I was updating these in the build but looks like not. I am working on updating these now, but the changes have caused some issues so may be a little while,

**Comment by sam-cogan** [comment]
This should now be resolved and the new update should roll out shortly.
