### ISSUE TITLE
Cannot bind argument to parameter 'Name' because it is an empty string.

### ISSUE THREAD

**Issue by Lahiri** [sam-cogan/arm-ttk-extension#19]
I get this error in a couple of test pipelines.
It's interesting that I run the same exact yaml pipeline for many other modules and it works perfectly.

![image](https://user-images.githubusercontent.com/1379165/87789727-c9103980-c83f-11ea-8e5a-2b75ce462675.png)

Is there any way to at least get more logging from the task?

**Comment by sam-cogan** [comment]
Can you provide some more details so I can look into this? Ideally the YAML you are using and the template you are testing against that generates this error.

**Comment by sam-cogan** [comment]
@Lahiri any chance you can provide an example template that causes this error?

**Comment by sam-cogan** [comment]
Will close this until some examples can be provided.
