### ISSUE TITLE
references to c:\temp\debug.txt

### ISSUE THREAD

**Issue by kevinbowman** [sam-cogan/arm-ttk-extension#2]
Hi Sam,

We get this issue when running the task:

![image](https://user-images.githubusercontent.com/19746567/74223514-c87ee000-4cae-11ea-91ef-403afbafeb93.png)

With or without enabling diagnostics on the pipeline.

Cheers

Kevin.

**Comment by sam-cogan** [comment]
Thanks for spotting this, version 1.0.11 is rolling out now that fixes this.
