### ISSUE TITLE
Request for a defined license

### ISSUE THREAD

**Issue by blinkyblink** [sam-cogan/arm-ttk-extension#21]
The LICENSE file in this repository is empty.
Additionally, the License link from the [Azure marketplace page](https://marketplace.visualstudio.com/items?itemName=Sam-Cogan.ARMTTKExtension) produces a 404.

I am requesting that you define an explicit license in one or both of these locations so everyone can know the terms that you are releasing this software under.

Thanks for the great work Sam.
Looking forward to using this extension :)

**Comment by sam-cogan** [comment]
Licence has been applied to the git repo now, will get it added to the extension page shortly
