### ISSUE TITLE
##[error]Failures found in test results

### ISSUE THREAD

**Issue by sudoom** [sam-cogan/arm-ttk-extension#27]
##[debug]Loading module from path 'D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.8\Export-NUnitXml.psm1'.
##[debug]Exporting function 'Export-NUnitXml'.
##[debug]Importing function 'Export-NUnitXml'.
##[debug]Loading module from path 'D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.8\invoke-ttk.psm1'.
##[debug]Exporting function 'Test-FolderContents'.
##[debug]Exporting function 'Invoke-TTK'.
##[debug]Importing function 'Invoke-TTK'.
##[debug]Importing function 'Test-FolderContents'.
##[debug]INPUT_TEMPLATELOCATION: 'D:\a\1\s\***\***\***\***.json'
##[debug]INPUT_RESULTLOCATION: 'D:\a\1\s'
##[debug]INPUT_INCLUDETESTS (empty)
##[debug]INPUT_SKIPTESTS (empty)
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Failures found in test results
##[debug]At D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.8\invoke-ttk.psm1:79 char:9
##[debug]+         throw "Failures found in test results"
##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : OperationStopped: (Failures found in test results:String) [], RuntimeException
##[debug]    + FullyQualifiedErrorId : Failures found in test results
##[debug] 
##[debug]Script stack trace:
##[debug]at Invoke-TTK, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.8\invoke-ttk.psm1: line 79
##[debug]at <ScriptBlock>, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.0.8\powershell.ps1: line 28
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RuntimeException: Failures found in test results
##[error]Failures found in test results
##[debug]Processed: ##vso[task.logissue type=error]Failures found in test results
##[debug]Processed: ##vso[task.complete result=Failed]

**Comment by sam-cogan** [comment]
This is normal, your template has failed one or more of the TTK test. Look at the test results to see which tests failed and asses whether you can fix it, or you want to skip that test.

**Comment by sudoom** [comment]
Thanks for your answer. I'll try this, everything goes fine, Thanks.
