### ISSUE TITLE
Support for jsonc files

### ISSUE THREAD

**Issue by kilasuit** [sam-cogan/arm-ttk-extension#28]
Looking into this [issue](https://github.com/Azure/arm-ttk/issues/200) (which actually started with looking at the code this extension) I think that with a minor change to this line we could support `.jsonc` files
https://github.com/sam-cogan/arm-ttk-extension/blob/875dc08cddabf74fb05e5aa6a6482fe51fc87544/task/invoke-ttk.psm1#L65

**Comment by sam-cogan** [comment]
Yep, that should be a pretty quick change, thanks for raising it.

**Comment by sam-cogan** [comment]
re-opening this, whilst the change is in the extension, the TTK doesn't actually test the files, need to wait for that to be updated
