### ISSUE TITLE
If Folder Path has a "." in the name it does not check the files

### ISSUE THREAD

**Issue by jf781** [sam-cogan/arm-ttk-extension#3]
Hi Sam - Thanks for putting this together.  I've added this to my pipeline and was able to get it to work but did noticed that if the template folder path had a "." in the name the tests did not seem to run. 

For example, if I had the templates in a folder "ARM.Templates" I got the response below. 

![image](https://user-images.githubusercontent.com/50719731/76411811-83f36c80-6360-11ea-8923-2c9497e7a8f3.png)

If I updated the folder name to "ARM-Templates" it worked as it should 

![image](https://user-images.githubusercontent.com/50719731/76411856-9ec5e100-6360-11ea-9a1d-546629c786ce.png)

I also did not get a test result output when the folder name was "ARM.Templates".  

Not a big deal since I was able to work around it but wanted to bring it to your attention.   Thanks again for the awesome work!!

**Comment by sam-cogan** [comment]
Hey, thanks for raising this. Will take a look into how we can fix this.

**Comment by sam-cogan** [comment]
This is fixed in the 1.0.36 release
