### ISSUE TITLE
Linux agent support?

### ISSUE THREAD

**Issue by esuomi** [sam-cogan/arm-ttk-extension#35]
As stated in the readme, this extension currently supports only Windows agents. As I'm not familiar with extension development for Azure DevOps, I'd be interested to understand how big of an effort would it be to make this extension work on Linux agents as well? Is the problem on the extension side or ARMTTK itself?

**Comment by sam-cogan** [comment]
My understanding is that to work cross platform we'd need to move to using a typescript extension. I think we can then call PS Core from TS, but I'd need to learn a bit of TypeScript.

**Comment by sam-cogan** [comment]
I know its been a while, but there is now a cross-platform version of the extension! [https://marketplace.visualstudio.com/items?itemName=Sam-Cogan.ARMTTKExtensionXPlatform](https://marketplace.visualstudio.com/items?itemName=Sam-Cogan.ARMTTKExtensionXPlatform )
