### ISSUE TITLE
Test failing but no details on error / issue provided

### ISSUE THREAD

**Issue by dgodfredson** [sam-cogan/arm-ttk-extension#36]
Get an error as follows with no indication of what / where the error is:

![image](https://user-images.githubusercontent.com/46269643/99480084-8310e100-29ab-11eb-8893-d252e30bcf35.png)

It successfully publishes the results as below but clicking the links just shows a 404 error

![image](https://user-images.githubusercontent.com/46269643/99480205-b9e6f700-29ab-11eb-9ad1-0113b64d6ac1.png)

Any tips / advice on getting more feedback on the errors? Ideally which test has failed would be great. Thanks

**Comment by Elthan** [comment]
You should be able to click this link and view it:

![image](https://user-images.githubusercontent.com/7212361/100448488-a83fd680-30b2-11eb-8aae-3e25e69b88ac.png)

**Comment by sam-cogan** [comment]
Yep sorry @Elthan is correct you can click on that link or you can go to the tests tab and see them there. 

I'll look into why that link doesn't work.

**Comment by Mwalima** [comment]
I have the same error

this is my .yml in the pipeline
pool:
  name: Azure Pipelines
steps:
- task: Sam-Cogan.ARMTTKExtension.RunARMTTKTests.RunARMTTKTests@1
  displayName: 'Run Azure RM TTK Tests'
  inputs:
    templatelocation: 'D:\a\1\s\RGDeployment\RGDeployment\parameterTemplates\*'
    resultLocation: 'D:\a\1\s\RGDeployment\RGDeployment\TestResults\'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit
    searchFolder: 'D:\a\1\s\RGDeployment\RGDeployment\TestResults\'
    mergeTestResults: true
    testRunTitle: 'Run Test'

![image](https://user-images.githubusercontent.com/4654945/100881758-9beebb80-34ae-11eb-8057-dd866225e3a1.png)

![image](https://user-images.githubusercontent.com/4654945/100881878-c3de1f00-34ae-11eb-855d-e38b35fd1a7f.png)

I dont see test-files in my folder like this
![image](https://user-images.githubusercontent.com/4654945/100882077-0acc1480-34af-11eb-8839-ece395808f8c.png)

**Comment by sam-cogan** [comment]
You need to make sure that your publish test results step always runs even when the test fails, so that it always publishes results. Add this to your results step:

Condition: always()

This will ensure the publishing will happen and your results will be in the tests tab an Azure dev ops.

**Comment by Mwalima** [comment]
i added the condition but it is still  giving the error

##[debug]Failures found in test results
##[debug]At D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.1.0\invoke-ttk.psm1:79 char:9
##[debug]+         throw "Failures found in test results"
##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : OperationStopped: (Failures found in test results:String) [], RuntimeException
##[debug]    + FullyQualifiedErrorId : Failures found in test results
##[debug] 
##[debug]Script stack trace:
##[debug]at Invoke-TTK, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.1.0\invoke-ttk.psm1: line 79
##[debug]at <ScriptBlock>, D:\a\_tasks\RunARMTTKTests_2ca36c0f-3e63-493e-a71a-de798e634733\1.1.0\powershell.ps1: line 28
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Management.Automation.RuntimeException: Failures found in test results
##[error]Failures found in test results


and i see no files in my directory

**Comment by sam-cogan** [comment]
This is expected, your are seeing an error because you are failing a test. 

I'm not sure what files you are taking about. The extension creates test results files that are consumed by the publish test step, but they won't persist after your run completes. You need to view the test results tab.

**Comment by Mwalima** [comment]
now its working. thanx
![image](https://user-images.githubusercontent.com/4654945/101140562-6c0cf880-3613-11eb-9d2e-20fede842c06.png)

**Comment by Mwalima** [comment]
But one more remark.
![image](https://user-images.githubusercontent.com/4654945/101145463-1a1ba100-361a-11eb-91ec-1a7593b50a2b.png)
you have to click on the link.
then you see the page
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-continuous-test-results-after-build?view=azure-devops#surface-test-results-in-the-tests-tab
And if you go back it suddely works.
