### ISSUE TITLE
Wildcards in test paths fail when not strictly following conventions

### ISSUE THREAD

**Issue by JaccoRademaker** [sam-cogan/arm-ttk-extension#4]
In our use case, we have a repository containing multiple ARM templates.
The extension currently allows wildcards, but then the templates have to be named `mainTemplate.json` or `azuredeploy.json`.
And with testing multiple files in different directories, where the files have the same name, it is hard to relate the test results to the tested template.

I had a look at the extension and I think this use case can be supported, while (hopefully) not breaking other use cases. For this, the logic of handling the wildcards should move to the extension. The toolkit would then only handle literal paths.

I have tried this by changing `task\powershell.ps1` and `task\Export-NUnitXml.ps1`.
What is the best way to show/propose these changes? Are you open to contributions?

**Comment by sam-cogan** [comment]
Hey Jacco, thanks for raising the issue. Is this a multiple templates nested within folders, or just multiple templates in a folder? For the later scenario this should work, as I hit the same issue when using the TTK with templates not following the naming conventions. If you can send me more details on the scenario I can look into.

That said, I am very happy to accept contributions, so please do feel free to submit a pull request!

**Comment by sam-cogan** [comment]
And I see you already did, let me check that out

**Comment by sam-cogan** [comment]
Resolved By #5
