### ISSUE TITLE
Testing the age of APIs doesn't work well

### ISSUE THREAD

**Issue by martingbrown** [sam-cogan/arm-ttk-extension#40]
"Api versions must be the latest or under 2 years old (730 days) - API version 2018-09-15 of Microsoft.DevTestLab/schedules is 870 days old in template file common-rg.template.json"

I've just had this error message. The 2018-09-15 may be 870 days old but according to [MS docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.devtestlab/schedules) it is still the latest version of that API as such this error looks like a false positive. It would be helpful if this rule had some kind of database of the APIs and what their versions are. Maybe then it would be possible to make the rule that it must be in the last three versions rather than giving an actual API age.

**Comment by sam-cogan** [comment]
Hello, this is an issue with the TTK its self, rather than the Azure DevOps extension, I would recommend raising this issue on the TTK project directly - https://github.com/Azure/arm-ttk.

You can skip this test with the extension using the Skip Tests property if  you wish.

**Comment by martingbrown** [comment]
Sorry just spotted my mistake when you posted. Ignore me.
