### ISSUE TITLE
Task name missing

### ISSUE THREAD

**Issue by Beelzenef** [sam-cogan/arm-ttk-extension#45]
hello there!

I've been working with your extension for a while and yesterday I noticed that, in the search panel in Azure DevOps, ARM TTK doesn't appear anymore.

It only shows up if you search it by "$taskdisplayname$", as if the variable wasnt set up in your release pipeline:

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/6389665/110616399-c8446300-8194-11eb-9ea8-65e9f2f82124.png)

Hope it helps, I don't want to leave without saying your extension is very cool and helpful, cheers!

**Comment by davidop** [comment]
I have the same problem. Hope you solve it soon. Great extension!

**Comment by sam-cogan** [comment]
Thanks for raising this, this has come from a recent change to the way I build the extension, I will get it sorted shortly

**Comment by sam-cogan** [comment]
Version 1.1.60 should fix this now, thanks for your patience.
