### ISSUE TITLE
Add an option to ignore last exit code

### ISSUE THREAD

**Issue by jikuja** [sam-cogan/arm-ttk-extension#47]
Please, add an option to ignore the exit code. 

Sometimes failing tests are ok but leaving task into failed state turn build into a **partially succeeded** state and the data for the **build's changes** is not updated. Then next build will contain same set of commit and new commit as **changes**. 

As far as I know ignoring errored exit code on task level is the only way to fix this problem.

**Comment by sam-cogan** [comment]
The latest release adds an ignoreExitCode property that if set to true will mean the task succeeds even if some tests fail
