### ISSUE TITLE
Comma separated -Skip list doesn't handle spaces after a comma

### ISSUE THREAD

**Issue by spoelstraethan** [sam-cogan/arm-ttk-extension#48]
I tried passing `DeploymentTemplate-Must-Not-Contain-Hardcoded-Uri, apiVersions-Should-Be-Recent`  expecting the task to be smart enough to trim spaces from the entries since the Skip syntax apparently requires the hyphenated versions (ie no whitespace internal to the entries), but unfortunately it failed so I had to remove the space, making the skip list VERY hard to read for humans.

**Comment by sam-cogan** [comment]
Yep, that's a fair point. Will look to trim them so you can make them more readable.

**Comment by sam-cogan** [comment]
This should be fixed in version 1.1.63 of the extension
