### ISSUE TITLE
How often does this extension get updated with latest TTK

### ISSUE THREAD

**Issue by jlevine-aba** [sam-cogan/arm-ttk-extension#53]
My fix in TTK got merged today -https://github.com/Azure/arm-ttk/pull/516 - this is a bug that affects most of our templates and we would like to remove it from our pipeline exclusions now that it works properly.  Do you only update this extension when a new full actual release of TTK happens, ad-hoc, etc?

**Comment by sam-cogan** [comment]
currently updating with the latest TTK is a manual process. For updating tests it's a pretty trivial re-build but for changes to the core TTK code it's a bit more involved as I need to make some manual changes. I'll look to get a new release done in the next day or so.
