### ISSUE TITLE
Static time 

### ISSUE THREAD

**Issue by Splaxi** [sam-cogan/arm-ttk-extension#55]
While testing the extension, I think we might have a minor bug in regards to the time of the test execution.

I ran all of these throughout the day, but they all report as being completed 01:00:00 AM:

<img width="88" alt="image" src="https://user-images.githubusercontent.com/8750181/143273201-d6b27db3-39d0-42c7-985b-2b7133b85a35.png">

I just ran some local tests, and did dot source the Export-NUnitXml function. And here I can see that the file that is being produced contains a valid time stamp, which matches up with the local time on my machine.

So could it be that the time on the Azure DevOps images are skewed? Could it be the Publish task for NUnit that doesn't understand the time stamp? Could it be the Test Plan (API) on Azure DevOps that doesn't understand the timestamp received?

**Comment by Splaxi** [comment]
Digging more into the details, it seems that the time attribute for all test-case entries in the NUnit XML file is either ignored (maybe the format is correct??) or that the Test Plan (API) is broken.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/8750181/143275226-a45b1fd3-7bf5-4623-b8b8-9491962e2deb.png">

**Comment by sam-cogan** [comment]
Thanks for finding that, I agree it does look like NUnit doesn't like the date/time format. I'll look into it.

**Comment by Splaxi** [comment]
@sam-cogan Did you get to look deeper into this?

**Comment by sam-cogan** [comment]
@Splaxi I had a look and there didn't seem to be an obvious cause, then I ran out of time. Will dedicate some time to it next week.

**Comment by Splaxi** [comment]
Thank you 👍
