### ISSUE TITLE
##[error]Invalid JSON primitive: .

### ISSUE THREAD

**Issue by poz1234** [sam-cogan/arm-ttk-extension#6]
When I try and run the extension in my build pipelines against either ARM templates that I have created or against one that I extracted directly from the Azure portal I get the following error.  I have tried with self hosted window based agents and Microsoft hosted agents.  

Mode                LastWriteTime         Length Name                                                                  

----                -------------         ------ ----                                                                  

-a----        3/25/2020   8:41 AM           6184 arm.json                                                              

##[error]Invalid JSON primitive: .

##[error]Cannot find path 'D:\a\1\s\ARM-TTK.XML' because it does not exist.

**Comment by sam-cogan** [comment]
Are you able to provide a copy of a template that causes this error? Please remove anything that may be confidential.

**Comment by CozyBadger** [comment]
@poz1234 I came accross this one a couple of days ago, too. In my case, the provided template file wasn't a valid json (missing quotes on one element), which caused the whole task to stop. Hence no test result was written -> file not found. Can you verify validity of your template with ConvertFrom-Json cmdlet?

**Comment by sam-cogan** [comment]
Closing this as there has been no response. Please re-open if you have an example I can test.

**Comment by roofiq** [comment]
Hey, I'm having same issue.
Here is error I'm getting:
```
Starting: RunARMTTKTests
==============================================================================
Task         : Run Azure RM TTK Tests
Description  : Run Azure Resource Manager Template Test Kit Tests against ARM Templates
Version      : 1.0.7
Author       : Sam Cogan
Help         : [More Information](https://github.com/sam-cogan/arm-ttk-extension/blob/master/README.md)
==============================================================================
##[error]Invalid JSON primitive: .
##[error]Failures found in test results
Finishing: RunARMTTKTests
```

I have a main template called. build.yml and a side one called build-step.yml. In this site template I have added a step with your task.
```
  - task: RunARMTTKTests@1
    inputs:
      templatelocation: '$(System.DefaultWorkingDirectory)\ARM\KeyVault.json'
      resultLocation: '$(System.DefaultWorkingDirectory)\results'
```

In ARM templates folder I have all the generic templates for different resource and other folder called ParametersExamples.
Even if in template location I'm passing only folder, it fails with same error.

Thanks for help
