### ISSUE TITLE
The test fails even though the apiVersion for "Microsoft.OperationsManagement/solutions" is recent.

### ISSUE THREAD

**Issue by akyamada-ms** [sam-cogan/arm-ttk-extension#61]
Hi, When I tested using this extended task, I encountered an event where the test failed even though it was the latest apiVersion.
The latest version of "Microsoft.OperationsManagement/solutions" is "2015-11-01-preview".
[API change log for Microsoft.OperationsManagement solutions - Bicep & ARM template reference | Microsoft Docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.operationsmanagement/change-log/solutions)

I checked the following document, but it seems that the API version is more than 2 years old. I think this is probably the cause.
[Template test cases for test toolkit - Azure Resource Manager | Microsoft Docs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-test-cases#use-recent-api-version)

So, in such a scenario, I want to skip the test only for the relevant part of the resource.
**Is it possible to skip only the tests for'type':'Microsoft.OperationsManagement / solutions' or'apiVersion': '2015-11-01-preview'?**

Specifying "apiVersions Should Be Recent" for "skipTests" will skip tests for other resources defined in the ARM template.
Is there a good way to skip only certain resources?

Thanks!

**Comment by sam-cogan** [comment]
This should be resolved now with the latest version of the TTK. If the latest version of the API is over 2 years old it should not fail.
