### ISSUE TITLE
build : The term 'build' is not recognized as the name of a cmdlet, function, script file, or operable program. Check  the spelling of the name, or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by shivanaru** [sam-cogan/arm-ttk-extension#67]
When I run this task - RunARMTTKTestsXPlat@1 - as part of the YAML pipeline I am seeing these below errors. I do not specify "build" anywhere in the .bicep files. Not sure what the expectation is? The PublishTestResults@2 is publishing the results though successfully.

##[error]build : The term 'build' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.

##[error]build : The term 'build' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.

##[error]At line:1 char:2
+  build D:\a\1\s\deploy\infra\application-insights.bicep
+  ~~~~~
    + CategoryInfo          : ObjectNotFound: (build:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by sam-cogan** [comment]
The "build" command I would guess is coming from bicep build which we use to transpile the bicep code to ARM before we run the tests. This issue might be caused by having the Azure CLI version of Bicep installed on your build machine, which has a slightly different syntax for running it. I have fixed this, but only in the new cross-platform version of this extension, which is the only one receiving updates now. I recommend you do switch over to the new version - https://marketplace.visualstudio.com/items?itemName=Sam-Cogan.ARMTTKExtensionXPlatform

**Comment by shivanaru** [comment]
Yeah I am using the cross platform version, if you look at the task name I specified. You think it should work now? Was the fix committed today?

**Comment by sam-cogan** [comment]
Ah, you've raised this issue against the old extension repo hence the confusion. 

If your using the cross platform extension then that's a different issue. 

The first thing I would AKS is if you have set the useAzBicep flag to true? If so then you need to ensure that bicep is installed on your build machine using the azure CLI, the extension won't do that for you. 

If you don't have that set to true then it should install the non azure CLI version for you. If that is the case can you please provide the full yaml for your task, and the full log from the output.

**Comment by shivanaru** [comment]
Hi Sam,
I did not set that flag to true explicitly. So it would be the default value I assume. Below is the complete yaml task and log report. (Reminder again - The publish result publishes the results fine which is confusing with correct test results. Attaching the task as well here.)

                # Run the ARM TTK tests
                - task: RunARMTTKTestsXPlat@1
                  enabled: true
                  displayName: 'Run ARM TTK tests'
                  inputs: 
                    templatelocation: '$(workingDirectory)' #The path to the files you want to test
                    resultLocation: '$(System.DefaultWorkingDirectory)/ARMTTKResults' #The path to output the test results format.
                    cliOutputResults: true
                    ignoreExitCode: true

                # Publish test results
                - task: PublishTestResults@2
                  enabled: true
                  displayName: 'Publish ARM TTK test results'
                  condition: always()
                  inputs: 
                    testResultsFormat: 'NUnit'
                    testResultsFiles: '$(System.DefaultWorkingDirectory)/ARMTTKResults/*.xml'

-----------------------------------------------
ADO log output below:

##[error]the spelling of the name, or if a path was included, verify that the path is correct and try again.

##[error]At line:1 char:2

##[error]At line:1 char:2

##[error]+  build D:\a\1\s\deploy\infra\storage-account.bicep

##[error]+  build D:\a\1\s\deploy\infra\storage-account.bicep

##[error]+  ~~~~~

##[error]+  ~~~~~

##[error]    + CategoryInfo          : ObjectNotFound: (build:String) [], CommandNotFoundException

##[error]    + CategoryInfo          : ObjectNotFound: (build:String) [], CommandNotFoundException

##[error]    + FullyQualifiedErrorId : CommandNotFoundException

##[error]    + FullyQualifiedErrorId : CommandNotFoundException

##[error] 

##[error] 

 D:\a\1\s\deploy\infra\bicepconfig.json passed all tests


 D:\a\1\s\deploy\infra\main.json passed all tests


 D:\a\1\s\deploy\infra\main.parameters.dev.json passed all tests


Script finished
Finishing: Run ARM TTK tests

**Comment by shivanaru** [comment]
@sam-cogan - Any update on this?

**Comment by sam-cogan** [comment]
Unfortunately I've not had time this week to look at this, hopefully I'll get some time later this week.

**Comment by sam-cogan** [comment]
So the only place in the code where the command "build" is used is the Bicep build command as I mentioned. The extension checks whether bicep is installed on the build agent and if it is not it downloads it from MS. First things, can you provide the whole of the output from the RunARMTTKTestsXPlat task so I can see what it is doing before the error. If you don't want to post it here feel free to email me at mail at samcogan dot com.

A few other things:

- Can you check if you do have Bicep already installed on the build agent, and whether it is the standard or Azure CLI version?
- If the Azure CLI version is installed, please set the useAzBicep flag to true
- It looks like your running this on a windows agent, if you have PowerShell core (PowerShell 7) installed on that machine, can you set the usePSCore property to true and run the task on PS Core

**Comment by shivanaru** [comment]
Sorry for the delay but setting the useAzBicep and usePSCore flags to true (since I am using Az CLI) made it work! Thank you very much for your time and response!
